#!/bin/bash
# Unpack the JWS distribution, move the relevant components into place
# then delete the rest
set -e

ADDED_DIR=/tmp/artifacts
DISTRIBUTION_ZIP="jws-application-servers-3.1.0-RHEL7-x86_64.zip"

mkdir -m0755 $JWS_HOME

unzip -q $ADDED_DIR/$DISTRIBUTION_ZIP

mv jws-3.1/tomcat7/* $JWS_HOME
mv jws-3.1/*.txt $JWS_HOME
mv jws-3.1/extras/jsvc $JWS_HOME/bin/
mv jws-3.1/extras/* $JWS_HOME/extras/

rm -rf jws-3.1

